# Generated by Django 4.2.4 on 2023-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reqcount',
            new_name='reqCount',
        ),
        migrations.AddField(
            model_name='user',
            name='totalCost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
